server:
  port: 8080

api:
  edamam:
    app-id: d6ed98ebXXXX
    app-key: 084a3f01861a7a309ffdba6da9e8ad79XXXX
    recipe-search-url: https://api.edamam.com/api/recipes/v2
  google:
    api-key: google_key

# Toggle for offline mode
features:
  offline-mode: false

spring:
  web:
    cors:
      allowed-origins:
        - "http://localhost:4200" # Adjust according to your frontend app's URL
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true
