server:
  port: 8080

api:
  edamam:
    app-id: d6ed98ebXXXX
    app-key: 084a3f01861a7a309ffdba6da9e8ad79XXXX
    recipe-search-url: https://api.edamam.com/api/nutrition-data
  google:
    api-key: google_key

useMockData: true

spring:
  spring:
    doc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        path: /swagger-ui.html
  web:
    cors:
      allowed-origins:
        - "http://localhost:4200"
        - "http://13.203.42.185"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true


