server:
  port: 8080

api:
  edamam:
    app-id: d6ed98eb
    app-key: 084a3f01861a7a309ffdba6da9e8ad79
    recipe-search-url: https://api.edamam.com/api/recipes/v2
  google:
    api-key: google_key

# Toggle for offline mode
features:
  offline-mode: false