name: Deploy Backend to AWS

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: docker build -t mealrecommendation .

    - name: Log in to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Push to ECR
      run: |
        docker tag mealrecommendation-backend:latest 340752798287.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mealrecommendation-backend:latest
        docker push 340752798287.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mealrecommendation-backend:latest

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ap-south-1

    - name: Deploy to ECS
      run: aws ecs update-service --cluster mealrecommendation-backend --service mealrecommendationservice --force-new-deployment
