name: Deploy Backend to AWS

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
    
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private

      - name: Build Docker image
        run: |
          docker build -t mealrecommendation .

      - name: Push to ECR
        run: |
          docker tag mealrecommendation:latest 340752798287.dkr.ecr.ap-south-1.amazonaws.com/mealrecommendation-backend:latest
          docker push 340752798287.dkr.ecr.ap-south-1.amazonaws.com/mealrecommendation-backend:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster mealrecommendation --service mealrecommendationservice --force-new-deployment
